pre-commit:
  parallel: true
  commands:
    # check:
    #   glob: "*.{js,ts,cjs,mjs,d.cts,d.mts,jsx,tsx,json,jsonc}"
    #   run: npx @biomejs/biome check --no-errors-on-unmatched --files-ignore-unknown=true --colors=off {push_files}
    lint:
      run: pnpm run lint:fix
    typecheck:
      run: pnpm run typecheck

commit-msg:
  commands:
    commitlint:
      run: pnpm commitlint --edit {1}